"""Exact finite checks for the research note random_walk_identity.tex.

Requires NetworkX. Run: python3 verify_random_walk_refinements.py
The enumeration examines all partitions of every connected Graph Atlas graph
on 2--7 vertices, not just refinements generated by the proposed construction.
All random-walk comparisons use integers or fractions, never floating point.
"""

from collections import Counter, defaultdict
from fractions import Fraction
from itertools import combinations
import json
from pathlib import Path

import networkx as nx


def partitions(n):
    """Restricted-growth encodings: each unlabeled set partition exactly once."""
    labels = [0] * n

    def visit(i, highest):
        if i == n:
            yield tuple(labels)
            return
        for label in range(highest + 2):
            labels[i] = label
            yield from visit(i + 1, max(highest, label))

    yield from visit(1, 0)


def minimum_vertex_cover(g):
    for size in range(len(g) + 1):
        for subset in combinations(g.nodes, size):
            cover = set(subset)
            if all(u in cover or v in cover for u, v in g.edges):
                return cover
    raise AssertionError("No cover found")


def double_and_glue(g, cover):
    """Glue two copies along the independent complement of a vertex cover."""
    assert all(u in cover or v in cover for u, v in g.edges)
    h = nx.Graph()
    projection = {}
    for vertex in g:
        for sheet in range(2 if vertex in cover else 1):
            node = (vertex, sheet)
            h.add_node(node)
            projection[node] = vertex
    for u, v in g.edges:
        for sheet in (0, 1):
            h.add_edge((u, sheet if u in cover else 0),
                       (v, sheet if v in cover else 0))
    return h, projection


def signed_double(g, cover, crossed_edges):
    h, projection = double_and_glue(g, cover)
    for u, v in crossed_edges:
        assert u in cover and v in cover
        h.remove_edge((u, 0), (v, 0))
        h.remove_edge((u, 1), (v, 1))
        h.add_edge((u, 0), (v, 1))
        h.add_edge((u, 1), (v, 0))
    nx.set_node_attributes(h, projection, "role")
    return h, projection


def verify_projection(h, g, projection):
    """Test the full one-step equality directly, for every starting vertex."""
    assert set(projection) == set(h)
    assert set(projection.values()) == set(g)
    for x in h:
        counts = Counter(projection[y] for y in h[x])
        for v in g:
            actual = Fraction(counts[v], h.degree[x])
            target = (Fraction(1, g.degree[projection[x]])
                      if g.has_edge(projection[x], v) else Fraction(0))
            assert actual == target, (x, v, actual, target)


def trajectory_law(g, start, projection, steps):
    states = {(start, (projection[start],)): Fraction(1)}
    for _ in range(steps):
        next_states = defaultdict(Fraction)
        for (x, history), probability in states.items():
            for y in g[x]:
                next_states[y, history + (projection[y],)] += (
                    probability / g.degree[x])
        states = next_states
    observed = defaultdict(Fraction)
    for (_, history), probability in states.items():
        observed[history] += probability
    return dict(observed)


def faithful_quotient(h, labels):
    """Build the quotient and independently test the transition definition."""
    if any(labels[u] == labels[v] for u, v in h.edges):
        return None
    g = nx.Graph()
    g.add_nodes_from(range(max(labels) + 1))
    g.add_edges_from((labels[u], labels[v]) for u, v in h.edges)
    for x in h:
        counts = Counter(labels[y] for y in h[x])
        # Equality with 1 / degree_G at every adjacent quotient vertex.
        for v in g[labels[x]]:
            if counts[v] * g.degree[labels[x]] != h.degree[x]:
                return None
    return g


def main():
    graphs = [g for g in nx.graph_atlas_g()
              if 2 <= len(g) <= 7 and nx.is_connected(g)]
    construction_count = 0
    example_data = []
    for g in graphs:
        cover = minimum_vertex_cover(g)
        h, projection = double_and_glue(g, cover)
        assert nx.is_connected(h)
        assert len(h) == len(g) + len(cover)
        assert h.number_of_edges() == 2 * g.number_of_edges()
        verify_projection(h, g, projection)
        assert (h.number_of_edges() - len(h) + 1
                == 2 * (g.number_of_edges() - len(g) + 1)
                + len(g) - len(cover) - 1)
        construction_count += 1

    partitions_by_n = {n: list(partitions(n)) for n in range(2, 8)}
    candidates = 0
    faithful = 0
    faithful_by_order = Counter()
    equality_cases = 0
    for h in graphs:
        for labels in partitions_by_n[len(h)]:
            quotient_order = max(labels) + 1
            if quotient_order < 2 or quotient_order == len(h):
                continue
            candidates += 1
            g = faithful_quotient(h, labels)
            if g is None:
                continue
            faithful += 1
            faithful_by_order[len(h)] += 1
            fibers = Counter(labels)
            cover = {v for v, size in fibers.items() if size > 1}
            assert all(u in cover or v in cover for u, v in g.edges)
            tau = len(minimum_vertex_cover(g))
            assert len(h) >= len(g) + tau
            assert h.number_of_edges() % g.number_of_edges() == 0
            degree = h.number_of_edges() // g.number_of_edges()
            assert degree >= 2
            for u, v in g.edges:
                edge_count = sum({labels[x], labels[y]} == {u, v}
                                 for x, y in h.edges)
                assert edge_count == degree
            if len(h) == len(g) + tau:
                equality_cases += 1
                assert degree == 2
                assert set(fibers.values()) <= {1, 2}
                assert len(cover) == tau

    for name, g in [("path_3", nx.path_graph(3)),
                    ("triangle", nx.complete_graph(3)),
                    ("star_4_leaves", nx.star_graph(4))]:
        cover = minimum_vertex_cover(g)
        h, projection = double_and_glue(g, cover)
        for x in h:
            assert trajectory_law(h, x, projection, 8) == trajectory_law(
                g, projection[x], {v: v for v in g}, 8)
        example_data.append({
            "name": name, "base_vertices": len(g),
            "base_edges": g.number_of_edges(),
            "cover": sorted(cover), "refined_vertices": len(h),
            "refined_edges": h.number_of_edges(),
            "refined_cycle_rank": h.number_of_edges() - len(h) + 1,
            "all_starting_vertices_path_law_verified_through_steps": 8,
        })

    # Independent isomorphism checks for the full classification of minimizers.
    # Node colors fix the base label, so only swaps inside fibers are allowed.
    signing_count = 0
    cover_count = 0
    for g in graphs:
        if len(g) > 5:
            continue
        tau = len(minimum_vertex_cover(g))
        for selected in combinations(g.nodes, tau):
            cover = set(selected)
            if not all(u in cover or v in cover for u, v in g.edges):
                continue
            induced = g.subgraph(cover)
            internal_edges = list(induced.edges)
            representatives = []
            for mask in range(1 << len(internal_edges)):
                crossed = [e for i, e in enumerate(internal_edges)
                           if mask & (1 << i)]
                h, projection = signed_double(g, cover, crossed)
                verify_projection(h, g, projection)
                assert nx.is_connected(h)
                signing_count += 1
                if not any(nx.is_isomorphic(
                        h, prior, node_match=lambda a, b: a["role"] == b["role"])
                           for prior in representatives):
                    representatives.append(h)
            beta = (induced.number_of_edges() - len(induced)
                    + nx.number_connected_components(induced))
            assert len(representatives) == 2 ** beta
            cover_count += 1

    k4 = nx.complete_graph(4)
    plain, _ = signed_double(k4, {0, 1, 2}, [])
    twisted, _ = signed_double(k4, {0, 1, 2}, [(0, 1)])
    assert not nx.is_isomorphic(plain, twisted)
    k4_examples = {
        "vertices_each": len(plain), "edges_each": plain.number_of_edges(),
        "plain_triangles": sum(nx.triangles(plain).values()) // 3,
        "twisted_triangles": sum(nx.triangles(twisted).values()) // 3,
        "nonisomorphic_even_without_role_labels": True,
    }

    # A history of genuine expansions: the degree is multiplicative.
    g = nx.path_graph(2)
    history = [{"vertices": len(g), "edges": g.number_of_edges()}]
    original_projection = {v: v for v in g}
    original = g.copy()
    for _ in range(5):
        cover = minimum_vertex_cover(g)
        h, projection = double_and_glue(g, cover)
        original_projection = {
            x: original_projection[projection[x]] for x in h}
        verify_projection(h, original, original_projection)
        g = h
        history.append({"vertices": len(g), "edges": g.number_of_edges()})

    result = {
        "networkx_version": nx.__version__,
        "construction_base_graphs_checked": construction_count,
        "base_graph_orders": [2, 7],
        "exhaustive_source_graphs_checked": len(graphs),
        "source_partitions_checked": candidates,
        "faithful_nontrivial_partitions": faithful,
        "faithful_partitions_by_source_order": dict(faithful_by_order),
        "vertex_bound_equality_cases": equality_cases,
        "counterexamples": 0,
        "examples": example_data,
        "classification_minimum_covers_checked": cover_count,
        "classification_sign_assignments_checked": signing_count,
        "classification_base_orders": [2, 5],
        "k4_distinct_optimal_refinements": k4_examples,
        "nested_history": history,
        "scope": "All connected unlabeled simple graphs on 2--7 vertices; "
                 "all their set partitions with 2 through n-1 blocks. "
                 "Computational checks supplement, not replace, the proof.",
    }
    output = Path(__file__).with_name("verification_results.json")
    output.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
